### ISSUE TITLE
Installation on Mac OS X 10.11.3

### ISSUE THREAD

**Issue by ec1112** [NikolausDemmel/tvseg#1]
Sorry if submitting an issue is not appropriate, please remove it if not. 

Trying to install tvseg, having trouble and wondering if you have any thoughts:
-Doing `brew install NikolausDemmel/devel/boost-libstdcxx` errors out on an SHA1 mismatch
-Doing `brew install NikolausDemmel/devel/qt5-libstdcxx` errors out during the make with:

```
Last 15 lines from /Users/.../Library/Logs/Homebrew/qt5-libstdcxx/02.make:
    virtual int qt_metacall(QMetaObject::Call, int, void **);
......
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtbase-make_first] Error 2
```

Doesn't seem to be a homebrew problem. Any ideas why the first checksum fails or why the library fails to build? Any thoughts would be appreciated. Thanks.

**Comment by NikolausDemmel** [comment]
> Sorry if submitting an issue is not appropriate, please remove it if not.

Sure. The only problem is that this project is rather unmaintained and I haven't worked on it for a while. Expect having to wrestle through some issues by yourself. But I hope to be able to give some guidance.

> -Doing brew install NikolausDemmel/devel/boost-libstdcxx errors out on an SHA1 mismatch

Not sure, no. Can you paste the full output to a gist or to pastebin or something?

> -Doing brew install NikolausDemmel/devel/qt5-libstdcxx errors out during the make with:

Same here.

In general, note that I only ever tried this on OS X 10.9. If I wanted to pick this up again I would do one of two things:
1. Try with more recent version of CUDA. The `...-libstdcxx` custom homebrew formulae were needed because CUDA 6.0 is not able to handle libc++, but from the CUDA 7.0 release notes it seems this is now fixed. So I would try with CUDA 7.0 or later and the default homebrew formulae for the dependencies. Note that you will have to adjust the `.pro` file, most notably [the section about the non-standard homebrew libraries](https://github.com/NikolausDemmel/tvseg/blob/master/tvseg.pro#L5-L27).
2. If the first doesn't help, I would try by recreating the `-libstdcxx` formulae from the current versions of the standard formulae for those libraries in homebrew. Take the latest formula, and adjust it such that it compiles with `libstdc++`. For example, in the current formula this seems to be the critical line (which I added on top of the default formula back in the day): https://github.com/NikolausDemmel/homebrew-devel/blob/master/qt5-libstdcxx.rb#L68

**Comment by NikolausDemmel** [comment]
Did you get anywhere?

**Comment by ec1112** [comment]
At the moment I'm trying other alternatives, but if I get this working I'll let you know exactly what I did. Thank you for you quick reply originally and taking the time to make suggestions as to how to get it working, this is truly appreciated.

**Comment by NikolausDemmel** [comment]
Sure. Good luck!
